#
#  Author: Hari Sekhon
#  Date: 2015-05-31 19:20:44 +0100 (Sun, 31 May 2015)
#
#  vim:ts=4:sts=4:sw=4:et
#

language: java
# doesn't provide oraclejdk6 any more because it's EOL as of Nov 2012
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

sudo: false

notifications:
  email: false

branches:
  only:
    - master

after_success:
  # JaCoCo gives error, skip for now and just use Cobertura:
  # [WARNING] Classes in bundle 'Utils' do no match with execution data. For report
  # generation the same class files must be used as at runtime.
  # [WARNING] Execution data for class HariSekhon/Utils does not match.
  #- mvn clean cobertura:cobertura jacoco:report coveralls:report
  - mvn clean cobertura:cobertura coveralls:report
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/centos-github/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/ubuntu-github/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/debian-github/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/
