#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2015-05-31 19:20:44 +0100 (Sun, 31 May 2015)
#
#  https://github.com/harisekhon/lib-java
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

language: java
# doesn't provide oraclejdk6 any more because it's EOL as of Nov 2012
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

after_success:
  # JaCoCo gives error, skip for now and just use Cobertura:
  # [WARNING] Classes in bundle 'Utils' do no match with execution data. For report
  # generation the same class files must be used as at runtime.
  # [WARNING] Execution data for class HariSekhon/Utils does not match.
  #- mvn clean cobertura:cobertura jacoco:report coveralls:report
  - mvn clean cobertura:cobertura coveralls:report
